### ISSUE TITLE
type compatibility should be checked at compile time

### ISSUE THREAD

**Issue by rogpeppe** [actgardner/gogen-avro#117]
The following [code](https://play.golang.org/p/Qqn7QjfYrbm) succeeds OK even though the field F1 has an incompatible type in each record. The compiler should do a better check than this - if we try to actually use the deserializer, we can get a panic.

```go
package main

import (
	"log"

	"github.com/actgardner/gogen-avro/compiler"
)

var s1 = `{
    "name": "R",
    "type": "record",
    "fields": [
        {
            "name": "F1",
            "type": "int"
        }
    ]
}`

var s2 = `{
    "name": "R",
    "type": "record",
    "fields": [
        {
            "name": "F1",
            "type": "string"
        }
    ]
}
`

func main() {
	_, err := compiler.CompileSchemaBytes([]byte(s1), []byte(s2))
	if err != nil {
		log.Fatalf("cannot compile: %v", err)
	}
	log.Printf("compiled OK")
}

```

Unless I've missed something, ISTM that the [RecordDefinition.IsReadableBy](https://github.com/actgardner/gogen-avro/blob/v6.3.1/schema/record.go#L200) implementation needs to do more than just check the record name.

**Comment by rogpeppe** [comment]
Here's an example in the Go playground of the deserialization failing with a caught panic: https://play.golang.org/p/77gY9C_QMhu

The error is:

    Panic at pc 4 - Unable to assign int to string field

At least the panic is caught, but it would be nicer if the error could mention the name of the incompatible field and what the type incompatibility is.

It seems that this issue applies to many schema incompatibilities, so I'll retitle this issue.

**Comment by actgardner** [comment]
This issue should be resolved on master now, I've fixed the IsReadableBy logic for records as well as unions. Let me know if you find any more examples, thanks for raising this.

**Comment by rogpeppe** [comment]
I'm sorry, but unfortunately this doesn't seem to have fixed the issue for me.
I tried out both the above pieces of code with gogen-avro v6.3.2-0.20200217180605-094ddb94693c+incompatible (the latest master, I believe) and I still get exactly the same behaviour as before.

**Comment by rogpeppe** [comment]
I added a test in a draft PR to demonstrate the issue: https://github.com/actgardner/gogen-avro/pull/125
